apiVersion: v1
kind: Service
metadata:
  name: supabase-auth
  namespace: eve
  labels:
    app.kubernetes.io/name: supabase-auth
spec:
  selector:
    app.kubernetes.io/name: supabase-auth
  ports:
    - name: http
      port: 9999
      targetPort: 9999
